export type RejectionReason =
  | "out_of_range"
  | "invalid_time_zone"
  | "version_too_low"
  | "record_not_found"
  | "record_before_started_on"
  | "invalid_entry_method"
  | "duplicate_photo_ids"
  | "photo_already_used"
  | "invalid_notice_type"
  | "invalid_target_on"
  // 推定し直しで料理の材料が置き換わっていた（料理の量の書き込みが前の材料を載せていた、前の材料の量を直そうとした）
  | "ingredients_replaced"
  // 推定を待っている食事（写真を待っている・推定中・翌日に推定）に料理を足そうとした、その料理と材料を直そうとした、推定し直しを待っている料理（推定中・翌日に推定）と、その材料を直そうとした
  | "awaiting_estimation"
  // 食事と読み分けていない文章を、会話として送り直そうとした
  | "not_classified_as_meal"
  // 返事を頼んでいない文章（読み分ける前、食事と読み分けた）を送り直そうとした
  | "reply_not_failed";
