#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
#
# ready-for-human の3件（#237 Sentry、#230 TestFlight の締め出し、#242 の Swift）を
# 順に確かめる。PR の作成と merge、ワークフローの起動、Issue へのコメントと閉じることは、
# この wizard が開いた画面で人が押す。wizard は GitHub に何も書かない。
# 入力と結果は ENV_FILE に残るので、途中で止めても、やり直すときに済んだ区切りを飛ばせる。

REPO="gn-t-k/nu-tori"
GH="https://github.com/${REPO}"
ENV_FILE="${TMPDIR:-/tmp}/nu-tori-verify-human-tickets.env"
OUT_DIR="${TMPDIR:-/tmp}/nu-tori-verify-human-tickets"
TOTAL_STAGES=16

# ── この wizard の道具 ────────────────────────────────────────────────────

# record KEY: 合否を聞き、ENV_FILE に ok か ng:<メモ> で残す
record() {
  local key="$1" memo=""
  if confirm "見えたとおりでしたか？"; then
    write_env "$key" "ok"
  else
    printf '  %s何が違いましたか（1行）:%s ' "$BOLD" "$RESET"
    read -r memo || true
    write_env "$key" "ng:${memo}"
  fi
}

# result KEY: 残した値（無ければ空）
result() { _existing "$1" || true; }

# skip_section N: 区切りを飛ばしたときに、段の番号を合わせる
skip_section() { _STAGE_INDEX=$((_STAGE_INDEX + $1)); }

# section_wanted KEY "名前": 前の回で済んでいれば、もう一度やるかを聞く
section_wanted() {
  if [[ "$(result "$1")" == "done" ]]; then
    _clear
    printf '\n'
    note "${2} は前の回で済んでいます。"
    confirm "もう一度やりますか？"
    return
  fi
  return 0
}

# copy_text FILE: 中身をクリップボードに写す（macOS の pbcopy があるとき）
copy_text() {
  if command -v pbcopy >/dev/null 2>&1; then
    pbcopy < "$1"
    printf '  %s✓ クリップボードに写しました%s\n' "$GREEN" "$RESET"
  else
    note "クリップボードに写せないので、${1} の中身を貼ってください"
  fi
}

# min_build_pr VALUE "理由": 本番の MINIMUM_APP_BUILD を VALUE にする PR を、人が GitHub の画面で作って merge する
min_build_pr() {
  local value="$1" reason="$2"
  say "本番の MINIMUM_APP_BUILD を ${value} にする PR を、GitHub の画面で作って merge します。"
  open_url "${GH}/edit/main/server/wrangler.jsonc"
  step "「env.production」の vars の \"MINIMUM_APP_BUILD\": の値を ${value} に書き換える"
  step "「Commit changes...」→ 題は「本番の MINIMUM_APP_BUILD を ${value} にする」"
  step "「Create a new branch for this commit and start a pull request」を選んで進む"
  step "PR の本文に次を書いて PR を作る:"
  note "  ${reason}（#230 の実機の確認）"
  step "必須のチェック（changes・ios・server）が通ったら「Merge pull request」"
  pause "merge したら Enter"
  open_url "${GH}/actions/workflows/deploy.yml"
  step "いちばん上の deploy の回で、development → shallow-check → production が緑になるのを待つ"
  pause "production が緑になったら Enter"
}

# line KEY "項目": コメントのチェックの1行
line() {
  local r; r=$(result "$1")
  case "$r" in
    ok)   printf -- '- [x] %s\n' "$2" ;;
    ng:*) printf -- '- [ ] %s。違った: %s\n' "$2" "${r#ng:}" ;;
    *)    printf -- '- [ ] %s（まだ）\n' "$2" ;;
  esac
}

# all_ok KEY...: すべて ok か
all_ok() { local k; for k in "$@"; do [[ "$(result "$k")" == "ok" ]] || return 1; done; }

# post_comment N FILE: Issue の画面を開き、コメントを貼ってもらう
post_comment() {
  local n="$1" file="$2"
  printf '\n%s── #%s に書くコメント ──%s\n' "$BOLD" "$n" "$RESET"
  sed 's/^/  /' "$file"
  printf '\n'
  copy_text "$file"
  open_url "${GH}/issues/${n}"
  step "下のコメント欄に貼って「Comment」を押す"
}

FOOTER=$'\n---\n_Generated by [Claude Code](https://claude.ai/code)_'

mkdir -p "$OUT_DIR"

banner "ready-for-human の3件を確かめる"

# ── #237 Sentry ───────────────────────────────────────────────────────────

if section_wanted SENTRY_DONE "#237 Sentry"; then

stage "#237 Sentry: 本番の新しい issue のアラートがあるか"
say "Sentry の組織 nu-tori-fv の、サーバー（Cloudflare Worker）のプロジェクトのアラートを見ます。"
open_url "https://nu-tori-fv.sentry.io/alerts/rules/"
step "アラートの一覧を、サーバーのプロジェクトで絞る"
step "次をすべて満たすアラートがあるか見る"
note "  - 種類が issue のアラート"
note "  - 条件に「A new issue is created」（新しい issue）が入っている"
note "  - 環境が production か、すべての環境"
note "  - 動きが、メールで知らせる（Issue Owners・Team・Member のどれでもよい）"
note "画面が変わっていて一覧が見つからなければ、左のメニューの Alerts（または Monitors）から辿ってください。"
if confirm "そのアラートはありましたか？"; then
  write_env SENTRY_CHANGED "なし"
else
  step "「Create Alert」→ issue の種類を選ぶ"
  step "Project はサーバーのもの、Environment は production"
  step "When: 「A new issue is created」"
  step "Then: 「Send a notification to」で自分（Member）か Issue Owners"
  step "名前は「本番の新しい issue をメールで知らせる」など。保存する"
  pause "保存したら Enter"
  write_env SENTRY_CHANGED "サーバーのプロジェクトに、production の新しい issue をメールで知らせる issue のアラートを足した"
fi
write_env SENTRY_ALERT "ok"

stage "#237 Sentry: テストの通知がメールに届くか"
step "そのアラートを開き、編集の画面の「Send Test Notification」を押す"
step "Sentry に登録したメールを開き、テストの通知が届いたか見る"
note "届かなければ、個人の通知の設定で、アラートの通知がメールでオンかも見てください:"
note "  https://nu-tori-fv.sentry.io/settings/account/notifications/"
pause "見たら Enter"
record SENTRY_MAIL
if [[ "$(result SENTRY_MAIL)" != "ok" ]]; then
  printf '  %s設定を直したなら、何を直したか（1行。無ければ空で Enter）:%s ' "$BOLD" "$RESET"
  fix=""
  read -r fix || true
  [[ -n "$fix" ]] && write_env SENTRY_CHANGED "$(result SENTRY_CHANGED)。${fix}"
fi

stage "#237 Sentry: 結果を Issue に書く"
{
  printf 'wizard で確かめた結果。\n\n'
  line SENTRY_ALERT "サーバーのプロジェクトに、本番の新しい issue をメールで知らせるアラートがある"
  line SENTRY_MAIL "アラートのテストの通知がメールに届いた"
  printf '\n変えた設定: %s\n%s\n' "$(result SENTRY_CHANGED)" "$FOOTER"
} > "$OUT_DIR/237.md"
post_comment 237 "$OUT_DIR/237.md"
if all_ok SENTRY_ALERT SENTRY_MAIL; then
  step "全部通ったので、コメントのあと「Close issue」で閉じる"
else
  warn "違ったところがあります。閉じずに、直すチケットを立てるようエージェントに頼んでください。"
fi
pause "済んだら Enter"
write_env SENTRY_DONE "done"

else skip_section 3; fi

# ── #230 TestFlight の締め出し ────────────────────────────────────────────

if section_wanted LOCKOUT_DONE "#230 TestFlight の締め出し"; then

stage "#230 準備: 締め出しの入った版を iPhone に入れる"
say "#243（締め出し）が main に入ったあとに、Xcode Cloud が配った版を使います。"
step "iPhone の TestFlight アプリで nu-tori を開き、いちばん新しいビルドを入れる"
step "版の欄の括弧の中の数（ビルド番号）を見る"
note "そのビルドが #243 の merge（2026-10-02 15:20 日本時間）より後にできたものか、App Store Connect の TestFlight でも見られます:"
note "  https://appstoreconnect.apple.com/apps"
ask APP_BUILD "入れたビルド番号（整数）:"
while ! [[ "$APP_BUILD" =~ ^[0-9]+$ ]]; do
  [[ -t 0 ]] || { warn "入力が終わりました"; exit 1; }
  ask APP_BUILD "整数で入れてください:"
done
write_env APP_BUILD "$APP_BUILD"

stage "#230 ふだんは締め出されない"
step "入れた版を開く"
say "いつものタイムラインが出れば合格です。"
pause "見たら Enter"
record LOCKOUT_NORMAL

stage "#230 本番の最低バージョンを上げる"
LOCK_VALUE=$((APP_BUILD + 1))
warn "deploy が済むと、TestFlight の版はすべて締め出されます（使うのは開発者だけ）。"
min_build_pr "$LOCK_VALUE" "入れた TestFlight の版（ビルド ${APP_BUILD}）が締め出されるかを確かめるため、一時的に上げる。確かめたら 0 に戻す"

stage "#230 締め出される"
step "nu-tori をいったんホームに戻し、もう一度前に出す"
say "全面の「アップデートしてください」の画面が出て、ほかを押せなければ合格です。"
pause "見たら Enter"
record LOCKOUT_SHOWN

stage "#230 電波が無くても締め出される"
step "機内モードにする（Wi-Fi も切れているか見る）"
step "nu-tori を上にスワイプして終了し、開き直す"
say "締め出しの画面が出れば合格です。"
pause "見たら Enter"
record LOCKOUT_OFFLINE
step "機内モードを切る"
pause "切ったら Enter"

stage "#230「TestFlight で更新」"
step "締め出しの画面のボタンの文字が「TestFlight で更新」か見る"
step "押すと TestFlight のアプリが開くか見る"
pause "見たら Enter"
record LOCKOUT_BUTTON

stage "#230 本番の最低バージョンを 0 に戻す"
min_build_pr 0 "#230 の確認が済んだので、一時的に上げた最低バージョンを 0 に戻す"

stage "#230 締め出しが解ける"
step "nu-tori に戻り、ホームに戻してからもう一度前に出す"
say "締め出しの画面が消えて、タイムラインに戻れば合格です。"
pause "見たら Enter"
record LOCKOUT_RELEASED

stage "#230 結果を Issue に書く"
{
  printf 'wizard で確かめた結果（TestFlight のビルド %s）。\n\n' "$(result APP_BUILD)"
  line LOCKOUT_NORMAL "ふだんは締め出されない"
  line LOCKOUT_SHOWN "MINIMUM_APP_BUILD をビルド番号 + 1 にすると締め出され、ほかを押せない"
  line LOCKOUT_OFFLINE "電波が無くても、開き直すと締め出される"
  line LOCKOUT_BUTTON "ボタンが「TestFlight で更新」で、押すと TestFlight が開く"
  line LOCKOUT_RELEASED "MINIMUM_APP_BUILD を 0 に戻すと解ける"
  printf '\n「App Store で更新」は、App Store で最初に公開したあとに確かめてここに書く。\n%s\n' "$FOOTER"
} > "$OUT_DIR/230.md"
post_comment 230 "$OUT_DIR/230.md"
if all_ok LOCKOUT_NORMAL LOCKOUT_SHOWN LOCKOUT_OFFLINE LOCKOUT_BUTTON LOCKOUT_RELEASED; then
  step "全部通ったので、コメントのあと「Close issue」で閉じる"
else
  warn "違ったところがあります。閉じずに、直すチケットを立てるようエージェントに頼んでください。"
fi
pause "済んだら Enter"
write_env LOCKOUT_DONE "done"

else skip_section 9; fi

# ── #242 Swift を上げるワークフロー ───────────────────────────────────────

if section_wanted SWIFT_DONE "#242 Swift"; then

stage "#242 Swift を上げるワークフローを手で起動する"
open_url "${GH}/actions/workflows/update-swift-packages.yml"
step "右の「Run workflow」→ Branch は main のまま →「Run workflow」"
step "始まった回を開き、prepare と publish が終わるまで待つ（数分〜数十分）"
note "上げるものも新しい major も無ければ、publish は飛ばされます（skipped）。"
pause "終わったら Enter"
ask SWIFT_RUN "その回の URL（ブラウザのアドレス欄から）:"
write_env SWIFT_RUN "$SWIFT_RUN"

stage "#242 Swift の PR を見る"
open_url "${GH}/pulls?q=is%3Apr+is%3Aopen+head%3Aupdate-swift-packages"
note "新しい major があったときは、needs-triage の Issue も立ちます:"
note "  ${GH}/issues?q=is%3Aissue+label%3Aneeds-triage"
say "PR があるとき、上げた依存に応じて次が揃っているか見ます（Files changed のタブ）。"
note "  - ios/NuToriCore/Package.swift と ios/OpenAPIGenerator/Package.swift の exact: の版"
note "  - それぞれの Package.resolved"
note "  - posthog-ios・sentry-cocoa を上げたなら、Xcode のプロジェクトの参照（project.pbxproj）と、その Package.resolved"
note "  - swift-openapi-generator を上げたなら、生成したクライアント（NuToriAPI/Generated）"
note "  - 本文に、依存ごとの前の版・新しい版・変更履歴へのリンク"
note "  - Checks のタブで check が走っている"
say "PR が無いときは、PR も Issue も立っていなければ合格です（上げるものが無かった）。"
note "check が全部通ると、App がこの PR を merge します。"
ask SWIFT_PR "PR の URL（無ければ「なし」）:"
write_env SWIFT_PR "$SWIFT_PR"
record SWIFT_OK

stage "#242 結果を Issue に書く"
{
  printf 'wizard で確かめた結果（Swift を上げるワークフロー）。\n\n'
  line SWIFT_OK "Swift を上げるワークフローを手で起動し、PR が仕様どおり出た（上げるものが無ければ、PR も Issue も立たない）"
  printf '\n- 起動した回: %s\n- PR: %s\n' "$(result SWIFT_RUN)" "$(result SWIFT_PR)"
  printf '\n残り（major の PR が残ること、落ちた PR の Issue、月曜の起動）は、10/5（月）の PR で確かめる。\n%s\n' "$FOOTER"
} > "$OUT_DIR/242.md"
post_comment 242 "$OUT_DIR/242.md"
note "#242 は月曜の確認が残るので、閉じません。"
pause "済んだら Enter"
write_env SWIFT_DONE "done"

else skip_section 3; fi

# ── 終わり ────────────────────────────────────────────────────────────────

stage "終わり"
for k in SENTRY_MAIL LOCKOUT_NORMAL LOCKOUT_SHOWN LOCKOUT_OFFLINE LOCKOUT_BUTTON LOCKOUT_RELEASED SWIFT_OK; do
  if [[ "$(result "$k")" == ng:* ]]; then
    warn "違ったところがあります。直すチケットを立てるよう、エージェントに頼んでください。"
    break
  fi
done
note "コメントの文面は ${OUT_DIR}、入力と結果は ${ENV_FILE} に残っています。要らなくなったら消してください。"
pause "Enter で終わる"

finish
