#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# #124「本物の Sign in with Apple を開発用と本番で通す」を1回通すための wizard。
# .env にも GitHub の秘密の値にも何も書かない。サインインがうまくいかないときだけ、
# Cloudflare の秘密の値（wrangler secret）を入れ直す。
# nu-tori のクローンの中で `bash scripts/wizards/124-sign-in-with-apple.sh` で動かす。

TOTAL_STAGES=8

ROOT=$(git rev-parse --show-toplevel 2>/dev/null || true)
if [[ -z "$ROOT" || ! -f "$ROOT/server/wrangler.jsonc" ]]; then
  printf '%snu-tori のクローンの中で動かしてください%s\n' "$RED" "$RESET" >&2
  exit 1
fi
SERVER_DIR="$ROOT/server"
# 秘密の値は Cloudflare に置き、ファイルには残さない
ENV_FILE="$(mktemp)"
trap 'rm -f "$ENV_FILE"' EXIT

ISSUE_URL="https://github.com/gn-t-k/nu-tori/issues/124"
REQUIRED_SECRETS=(BETTER_AUTH_SECRET APPLE_TEAM_ID APPLE_KEY_ID APPLE_PRIVATE_KEY APPLE_REFRESH_TOKEN_KEYS)

# wr ENV ARGS... は、server/ で wrangler を動かす。ENV が空なら開発用、production なら本番
wr() {
  local env="$1"; shift
  if [[ -n "$env" ]]; then
    (cd "$SERVER_DIR" && pnpm exec wrangler "$@" --env "$env")
  else
    (cd "$SERVER_DIR" && pnpm exec wrangler "$@")
  fi
}

env_label() { if [[ -n "$1" ]]; then printf '本番'; else printf '開発用'; fi; }
# Worker と D1 は、どちらの環境も同じ名前にしている（wrangler.jsonc）
worker_name() { if [[ -n "$1" ]]; then printf 'nu-tori-production'; else printf 'nu-tori-development'; fi; }
tail_command() {
  if [[ -n "$1" ]]; then printf 'cd server && pnpm exec wrangler tail --env production --format pretty'
  else printf 'cd server && pnpm exec wrangler tail --format pretty'; fi
}

# d1_value ENV SQL は、1行1列の結果を数で返す。ID や暗号文は出さない
d1_value() {
  local env="$1" sql="$2" json
  json=$(wr "$env" d1 execute "$(worker_name "$env")" --remote --json --command "$sql" 2>/dev/null) || return 1
  printf '%s' "$json" | node -e '
    let s = ""; process.stdin.on("data", (d) => (s += d)).on("end", () => {
      const row = JSON.parse(s)[0].results[0];
      process.stdout.write(String(Object.values(row)[0]));
    });'
}

session_count() { d1_value "$1" 'SELECT COUNT(*) AS n FROM "session"'; }
token_count() { d1_value "$1" 'SELECT COUNT(*) AS n FROM apple_refresh_tokens'; }
# いちばん新しいセッションの人に、Apple のリフレッシュトークンが保存されているか（1 か 0）
latest_session_has_token() {
  d1_value "$1" 'SELECT EXISTS (SELECT 1 FROM apple_refresh_tokens WHERE account_id = (SELECT "userId" FROM "session" ORDER BY "createdAt" DESC LIMIT 1)) AS ok'
}

# put_secret ENV NAME は、標準入力の値を秘密の値に置く
put_secret() {
  local env="$1" name="$2"
  if wr "$env" secret put "$name" >/dev/null; then
    printf '  %s✓ put%s %s（%s）\n' "$GREEN" "$RESET" "$name" "$(env_label "$env")"
  else
    warn "$name を置けませんでした。wrangler の出力を見てください"
    return 1
  fi
}

reput_apple_key() {
  local env="$1" key_file
  confirm "$(env_label "$env")の APPLE_TEAM_ID・APPLE_KEY_ID・APPLE_PRIVATE_KEY を入れ直しますか？" || return 0
  open_url "https://developer.apple.com/account"
  step "Membership details の Team ID（10文字）をコピーする"
  ask APPLE_TEAM_ID "Team ID を貼る:"
  open_url "https://developer.apple.com/account/resources/authkeys/list"
  step "Sign in with Apple を有効にした鍵を開き、Key ID（10文字）をコピーする"
  step "その鍵の Configure で、Primary App ID が app.nu-tori か確かめる"
  ask APPLE_KEY_ID "Key ID を貼る:"
  note "鍵のファイル（AuthKey_${APPLE_KEY_ID}.p8）は、作ったときに1度だけダウンロードできます。"
  note "手元に無ければ、鍵を作り直し、開発用と本番の両方に入れ直してください。"
  ask KEY_PATH "鍵のファイルのパス（空なら ~/Downloads/AuthKey_${APPLE_KEY_ID}.p8）:"
  key_file="${KEY_PATH:-$HOME/Downloads/AuthKey_${APPLE_KEY_ID}.p8}"
  key_file="${key_file/#\~/$HOME}"
  if [[ ! -f "$key_file" ]] || ! grep -q "BEGIN PRIVATE KEY" "$key_file"; then
    warn "$key_file は .p8 の鍵に見えません。入れ直しをやめます"
    return 0
  fi
  printf '%s' "$APPLE_TEAM_ID" | put_secret "$env" APPLE_TEAM_ID
  printf '%s' "$APPLE_KEY_ID" | put_secret "$env" APPLE_KEY_ID
  # 改行ごとそのまま置く
  put_secret "$env" APPLE_PRIVATE_KEY < "$key_file"
}

regenerate_refresh_token_keys() {
  local env="$1" count
  count=$(token_count "$env" || echo "?")
  if [[ "$count" != "0" ]]; then
    warn "apple_refresh_tokens にもう ${count} 行あります。鍵を替えると、その行を復号できなくなります"
    warn "wizard では替えません。鍵を足すときは「2:<新しい鍵>,1:<今の鍵>」のように並べます"
    return 0
  fi
  confirm "$(env_label "$env")の APPLE_REFRESH_TOKEN_KEYS を新しい鍵（版 1）で置き直しますか？" || return 0
  printf '1:%s' "$(openssl rand -base64 32)" | put_secret "$env" APPLE_REFRESH_TOKEN_KEYS
}

# サインインに失敗したときの見立て。セッションができたかで、どこで止まったかを分ける
diagnose() {
  local env="$1" sessions_before="$2" sessions_after="$3" reply
  printf '\n'
  if [[ "$sessions_after" == "$sessions_before" ]]; then
    warn "セッションができていません。ID トークンの確認で止まったか、要求が届いていません"
    say "tail に POST /v1/sessions が出ていれば、状態コードを見てください"
    step "401: ID トークンを受け付けなかった。APPLE_BUNDLE_ID と、アプリの Bundle ID を突き合わせる"
    note "   wrangler.jsonc: $(grep -o '"APPLE_BUNDLE_ID": "[^"]*"' "$SERVER_DIR/wrangler.jsonc" | head -n1)"
    note "   Xcode: $(grep -o 'PRODUCT_BUNDLE_IDENTIFIER = "app.nu-tori"' "$ROOT/ios/NuTori.xcodeproj/project.pbxproj" | head -n1)"
    step "要求が出ていない: Apple の画面での失敗か、別の環境につないでいます"
    note "   デバッグビルドは開発用、TestFlight の版は本番につながります"
    note "   App ID に Sign in with Apple の Capability があるか確かめてください"
    return 0
  fi
  warn "セッションはできましたが、Apple のリフレッシュトークンが保存されていません"
  say "認可コードの交換か、トークンの保存で止まっています。tail に出た文はどれでしたか？"
  step "1) 「Apple の認可コードの交換に失敗した: 400」（500）: 鍵か Team ID が違う"
  step "2) 「APPLE_REFRESH_TOKEN_KEYS は…」「…の鍵が無い」（500）: 暗号化の鍵の形が違う"
  step "3) 401: Apple が認可コードを受け付けなかった（期限切れか使い回し）"
  step "4) わからない・ほか"
  ask CHOICE "番号:"
  reply="$CHOICE"
  case "$reply" in
    1) reput_apple_key "$env" ;;
    2) regenerate_refresh_token_keys "$env" ;;
    3) say "もう一度サインインしてください。続けて出るなら、APPLE_BUNDLE_ID を確かめてください" ;;
    *) say "tail の例外の文と、Sentry（nu-tori のサーバーのプロジェクト）の報告を見てください"
       note "見立てが付いたら、この wizard を Ctrl-C で止め、直してから動かし直せます" ;;
  esac
}

# sign_in_round ENV は、サインインを1回試し、トークンの保存までを DB で確かめる
sign_in_round() {
  local env="$1" before after has_token
  while true; do
    before=$(session_count "$env") || { warn "D1 を読めませんでした（wrangler のログインを確かめてください）"; return 1; }
    say "別のターミナルで、ログを流しておきます:"
    note "   $(tail_command "$env")"
    note "   （ログは手元で見るだけにし、Issue や PR に貼らない）"
    pause "流し始めたら Enter"
    step "iPhone の nu-tori で「Appleで続ける」を押し、Apple の画面を最後まで進める"
    pause "押し終えたら Enter"
    after=$(session_count "$env") || after="$before"
    has_token=$(latest_session_has_token "$env" || echo 0)
    if [[ "$after" != "$before" && "$has_token" == "1" ]]; then
      printf '  %s✓ セッションができ、Apple のリフレッシュトークンが保存されました%s\n' "$GREEN" "$RESET"
      if confirm "iPhone の画面がタイムラインに移りましたか？"; then
        return 0
      fi
      warn "サーバーは済んでいます。アプリの側の問題なので、#124 とは別に見てください"
      return 0
    fi
    diagnose "$env" "$before" "$after"
    confirm "直したら、もう一度サインインを試しますか？" || return 1
  done
}

check_secrets() {
  local env="$1" list missing=()
  list=$(wr "$env" secret list 2>/dev/null) || { warn "$(worker_name "$env") の秘密の値を一覧できませんでした"; return 1; }
  for name in "${REQUIRED_SECRETS[@]}"; do
    grep -q "\"$name\"" <<<"$list" || missing+=("$name")
  done
  if (( ${#missing[@]} )); then
    warn "$(worker_name "$env") に無い秘密の値: ${missing[*]}"
    return 1
  fi
  printf '  %s✓%s %s: 必要な秘密の値がそろっています\n' "$GREEN" "$RESET" "$(worker_name "$env")"
}

DEV_RESULT="未確認"
PROD_RESULT="未確認"

banner "#124 本物の Sign in with Apple を開発用と本番で通す"

# ── 1 ────────────────────────────────────────────────────────────────────
stage "準備: wrangler と依存"
say "D1 とログを見るので、server/ の wrangler を使います。"
if [[ ! -d "$SERVER_DIR/node_modules" ]]; then
  step "server/ の依存を入れます"
  (cd "$SERVER_DIR" && pnpm install --frozen-lockfile)
fi
if ! wr "" whoami >/dev/null 2>&1; then
  step "Cloudflare にログインします（ブラウザが開きます）"
  wr "" login
fi
wr "" whoami | grep -iE "account|email" | head -n 3 || true
pause "nu-tori の Cloudflare のアカウントなら Enter"

# ── 2 ────────────────────────────────────────────────────────────────────
stage "Apple Developer: App ID と鍵"
open_url "https://developer.apple.com/account/resources/identifiers/list"
step "Identifiers で app.nu-tori を開き、Capabilities の Sign in with Apple に印があるか確かめる"
open_url "https://developer.apple.com/account/resources/authkeys/list"
step "Keys に、Sign in with Apple を有効にした鍵があるか確かめる"
step "その鍵の Configure で、Primary App ID が app.nu-tori か確かめる"
note "Key ID は、開発用と本番の APPLE_KEY_ID に入れた値と同じはずです（違えば、あとの段で入れ直せます）"
pause "確かめたら Enter"

# ── 3 ────────────────────────────────────────────────────────────────────
stage "Worker と秘密の値"
open_url "https://github.com/gn-t-k/nu-tori/actions/workflows/deploy.yml"
step "#139 のマージより後の deploy が、development と production の両方で緑か確かめる"
pause "確かめたら Enter"
check_secrets "" || warn "開発用の秘密の値が足りません。wrangler secret put で置いてから続けてください"
check_secrets "production" || warn "本番の秘密の値が足りません。wrangler secret put --env production で置いてから続けてください"
pause "続けるなら Enter"

# ── 4 ────────────────────────────────────────────────────────────────────
stage "開発用: デバッグビルドを実機に入れる"
say "デバッグビルドは api-dev.nu-tori.app（開発用）につながります。"
step "Mac の Xcode で ios/NuTori.xcodeproj を開く"
step "実機を選び、スキーム NuTori（Debug）で Run する"
step "アプリが開き、サインインの画面が出るところまで進める"
pause "サインインの画面が出たら Enter"

# ── 5 ────────────────────────────────────────────────────────────────────
stage "開発用: サインインして保存を確かめる"
if sign_in_round ""; then DEV_RESULT="済み"; else DEV_RESULT="未完了"; fi
pause "次へ進むなら Enter"

# ── 6 ────────────────────────────────────────────────────────────────────
stage "本番: TestFlight の版を入れる"
say "TestFlight と App Store の版は api.nu-tori.app（本番）につながります。"
open_url "https://appstoreconnect.apple.com/apps"
step "nu-tori → TestFlight で、#139 のマージより後の main から作った版があるか確かめる"
note "無ければ、Xcode Cloud の「main から内部テスト」を手で始め、配られるのを待つ"
step "iPhone の TestFlight アプリで、その版を入れる（デバッグビルドとは置き換わります）"
pause "サインインの画面が出たら Enter"

# ── 7 ────────────────────────────────────────────────────────────────────
stage "本番: サインインして保存を確かめる"
warn "ほかのテストユーザーが同じときにサインインすると、見立てがずれることがあります"
if sign_in_round "production"; then PROD_RESULT="済み"; else PROD_RESULT="未完了"; fi
pause "次へ進むなら Enter"

# ── 8 ────────────────────────────────────────────────────────────────────
stage "#124 を閉じる"
say "開発用: $DEV_RESULT / 本番: $PROD_RESULT"
if [[ "$DEV_RESULT" == "済み" && "$PROD_RESULT" == "済み" ]]; then
  open_url "$ISSUE_URL"
  step "受け入れ条件の2つにチェックを入れる"
  step "次のコメントを付けて閉じる（アカウント ID やログの本文は貼らない）"
  printf '\n%s' "$DIM"
  cat <<'COMMENT'
    開発用（デバッグビルド）と本番（TestFlight の版）の両方で、本物の Sign in with Apple を通した。
    どちらも POST /v1/sessions が 201 を返し、Apple のリフレッシュトークンが
    apple_refresh_tokens に保存されたことを、D1 で確かめた。
COMMENT
  printf '%s\n' "$RESET"
  note "この wizard は1回きりのものです。済んだら scripts/wizards/124-sign-in-with-apple.sh を消してかまいません"
else
  warn "済んでいない環境があります。直してから、この wizard を動かし直してください"
fi
pause "終えるなら Enter"

finish
