name: deploy

on:
  push:
    branches: [main]
    # 必須のチェックではないので、ワークフローの paths で飛ばしてよい
    paths:
      - "server/**"
      - "shared/**"
      - ".github/workflows/deploy.yml"
      - ".github/workflows/deploy-worker.yml"
  workflow_dispatch:

concurrency:
  group: deploy
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  development:
    uses: ./.github/workflows/deploy-worker.yml
    with:
      environment: development
      wrangler-env: ""
      url: https://api-dev.nu-tori.app
    secrets: inherit

  production:
    needs: development
    uses: ./.github/workflows/deploy-worker.yml
    with:
      environment: production
      wrangler-env: production
      url: https://api.nu-tori.app
    secrets: inherit
